/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['wheel.js']) {
  _$jscoverage['wheel.js'] = [];
  _$jscoverage['wheel.js'][1] = 0;
  _$jscoverage['wheel.js'][3] = 0;
  _$jscoverage['wheel.js'][5] = 0;
  _$jscoverage['wheel.js'][6] = 0;
  _$jscoverage['wheel.js'][7] = 0;
  _$jscoverage['wheel.js'][8] = 0;
  _$jscoverage['wheel.js'][9] = 0;
  _$jscoverage['wheel.js'][10] = 0;
  _$jscoverage['wheel.js'][11] = 0;
  _$jscoverage['wheel.js'][13] = 0;
  _$jscoverage['wheel.js'][14] = 0;
  _$jscoverage['wheel.js'][21] = 0;
  _$jscoverage['wheel.js'][22] = 0;
  _$jscoverage['wheel.js'][23] = 0;
  _$jscoverage['wheel.js'][24] = 0;
  _$jscoverage['wheel.js'][25] = 0;
  _$jscoverage['wheel.js'][28] = 0;
  _$jscoverage['wheel.js'][29] = 0;
  _$jscoverage['wheel.js'][34] = 0;
  _$jscoverage['wheel.js'][35] = 0;
  _$jscoverage['wheel.js'][40] = 0;
  _$jscoverage['wheel.js'][41] = 0;
}
_$jscoverage['wheel.js'][1]++;
"use strict";
_$jscoverage['wheel.js'][3]++;
(function (exports) {
  _$jscoverage['wheel.js'][5]++;
  exports.Wheel = (function (newMaxWheelDiameter) {
  _$jscoverage['wheel.js'][6]++;
  var MIN_NUM_SPOKES = 8;
  _$jscoverage['wheel.js'][7]++;
  var MAX_NUM_SPOKES = 1000;
  _$jscoverage['wheel.js'][8]++;
  var maxWheelDiameter = newMaxWheelDiameter > 0? newMaxWheelDiameter: 100;
  _$jscoverage['wheel.js'][9]++;
  var wheelDiameter = maxWheelDiameter * 0.5;
  _$jscoverage['wheel.js'][10]++;
  var hubDiameter = 0.25 * wheelDiameter;
  _$jscoverage['wheel.js'][11]++;
  var numSpokes = 8;
  _$jscoverage['wheel.js'][13]++;
  this.getState = (function () {
  _$jscoverage['wheel.js'][14]++;
  return ({maxWheelDiameter: maxWheelDiameter, wheelDiameter: wheelDiameter, hubDiameter: hubDiameter, numSpokes: numSpokes, spokeLength: 0.5 * wheelDiameter - 0.5 * hubDiameter});
});
  _$jscoverage['wheel.js'][21]++;
  this.setState = (function (newWheelState) {
  _$jscoverage['wheel.js'][22]++;
  maxWheelDiameter = newWheelState.maxWheelDiameter;
  _$jscoverage['wheel.js'][23]++;
  wheelDiameter = newWheelState.wheelDiameter;
  _$jscoverage['wheel.js'][24]++;
  hubDiameter = newWheelState.hubDiameter;
  _$jscoverage['wheel.js'][25]++;
  numSpokes = newWheelState.numSpokes;
});
  _$jscoverage['wheel.js'][28]++;
  this.setWheelDiameter = (function (newWheelDiameter) {
  _$jscoverage['wheel.js'][29]++;
  return ! isNaN(newWheelDiameter) && newWheelDiameter >= 4 * hubDiameter && newWheelDiameter <= maxWheelDiameter? wheelDiameter = newWheelDiameter: 0;
});
  _$jscoverage['wheel.js'][34]++;
  this.setHubDiameter = (function (newHubDiameter) {
  _$jscoverage['wheel.js'][35]++;
  return ! isNaN(newHubDiameter) && newHubDiameter * 4 <= wheelDiameter && newHubDiameter > 0? hubDiameter = newHubDiameter: 0;
});
  _$jscoverage['wheel.js'][40]++;
  this.setNumSpokes = (function (newNumSpokes) {
  _$jscoverage['wheel.js'][41]++;
  return ! isNaN(newNumSpokes) && newNumSpokes >= MIN_NUM_SPOKES && newNumSpokes <= MAX_NUM_SPOKES? numSpokes = newNumSpokes: 0;
});
});
})(typeof exports === "undefined"? this.Wheel = {}: exports);
_$jscoverage['wheel.js'].source = ["\"use strict\";","","(function(exports){","","  exports.Wheel = function (newMaxWheelDiameter) {","    var MIN_NUM_SPOKES = 8;","    var MAX_NUM_SPOKES = 1000;","    var maxWheelDiameter = newMaxWheelDiameter &gt; 0 ? newMaxWheelDiameter : 100;","    var wheelDiameter = maxWheelDiameter * 0.5;","    var hubDiameter = 0.25 * wheelDiameter;","    var numSpokes = 8;","","    this.getState = function () {","      return {maxWheelDiameter : maxWheelDiameter,","        wheelDiameter : wheelDiameter,","        hubDiameter : hubDiameter,","        numSpokes : numSpokes,","        spokeLength : 0.5 * wheelDiameter - 0.5 * hubDiameter};","    };","","    this.setState = function (newWheelState) {","      maxWheelDiameter = newWheelState.maxWheelDiameter;","      wheelDiameter = newWheelState.wheelDiameter;","      hubDiameter = newWheelState.hubDiameter;","      numSpokes = newWheelState.numSpokes;","    };","","    this.setWheelDiameter = function (newWheelDiameter) {","      return !isNaN(newWheelDiameter) &amp;&amp;","        newWheelDiameter &gt;= 4 * hubDiameter &amp;&amp;","        newWheelDiameter &lt;= maxWheelDiameter ? wheelDiameter = newWheelDiameter : 0;","    };","","    this.setHubDiameter = function (newHubDiameter) {","      return !isNaN(newHubDiameter) &amp;&amp;","        newHubDiameter * 4 &lt;= wheelDiameter &amp;&amp;","        newHubDiameter &gt; 0 ? hubDiameter = newHubDiameter : 0;","    };","","    this.setNumSpokes = function (newNumSpokes) {","      return !isNaN(newNumSpokes) &amp;&amp;","        newNumSpokes &gt;= MIN_NUM_SPOKES &amp;&amp;","        newNumSpokes &lt;= MAX_NUM_SPOKES ? numSpokes = newNumSpokes : 0;","    };","  };","","})(typeof exports === 'undefined' ? this.Wheel = {}: exports);"];
